sitefeed:
  class: sfPropelRouteCollection
  options:
    model:                Sitefeed
    module:               sitefeed
    prefix_path:          sitefeed
    column:               id
    with_wildcard_routes: true

feed:
  class: sfPropelRouteCollection
  options:
    model:                Feed
    module:               feed
    prefix_path:          feed
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
