
propel:
   site:
      id:		~
      title:
         type: varchar(255)
      baseurl:
         type: varchar(255)
         required: true      

   feed:
      id:		~
      title:
         type: varchar(255)
      link:
         type: varchar(255)
         required: true
         index: unique
      website:
         type: varchar(255)
         required: true
      type:
         type: varchar(32)

   sitefeed:
      site_id:
         type: integer
         foreignTable: site
         foreignReference: id
         required: true
      feed_id:
         type: integer
         foreignTable: feed
         foreignReference: id
         required: true
      collection:
         type: varchar(32)

   item:
      id:	~
      feed_id:
         type: integer
         foreignTable: feed
         foreignReference: id
         required: true
      atomid:
         type: varchar(255)
         required: true
         index: unique     
      title:
         type: longvarchar
         required: true
      link:
         type: varchar(255)
         required: true
         index: unique
      description:
         type: longvarchar
         required: true
      published:
         type: timestamp
         required: true			
